### ISSUE TITLE
cannot start slave... timeout

### ISSUE THREAD

**Issue by Bubba210** [deevus/docker-plex-remote-transcoder#11]
Slave fails to start, getting a connection timed out error with no further information...

`/usr/bin/docker-current: Error response from daemon: connection timed out.`

using `docker run \
> --name plex_slave \
> --restart=always \
> --network=host \
> -e TZ="Americas/Los_Angeles" \
> -e MASTER_IP="192.168.0.25" \
> -e SLAVE_IP="192.168.0.60" \
> -e SLAVE_PORT="22" \
> -e SLAVE_USER="plex" \
> -e PLEX_UID="1010" \
> -e PLEX_GID="1001" \
> -v /mnt/configs/plex/config:/config \
> -v /mnt/configs/plex/transcode/tmp:/transcode \
> -v nfs_completed_Movies:/data/movies \
> -v nfs_completed_TV:/data/tvshows \
> deevus/plex-remote-transcoder:slave-latest`

**Comment by deevus** [comment]
Seems like a docker related issue?

**Comment by Bubba210** [comment]
yup.  confirmed docker version/NFS issue...
