### ISSUE TITLE
Error when pulling docker image

### ISSUE THREAD

**Issue by bighungry** [deevus/docker-plex-remote-transcoder#14]
Not sure if this is the right place for this or not, but when I try to pull this docker image, I get this error: traveler:~ austin$ docker pull deevus/plex-remote-transcoder
Using default tag: latest
Error response from daemon: manifest for deevus/plex-remote-transcoder:latest not found

I got the pull command straight from https://hub.docker.com/r/deevus/plex-remote-transcoder.

Am I missing something? Thanks!

**Comment by deevus** [comment]
No problem. Check the tags here: https://hub.docker.com/r/deevus/plex-remote-transcoder/tags

**Comment by bighungry** [comment]
Doh! The one place I didn’t look. Thank you so much!

**Comment by deevus** [comment]
It's cool
